export let productos =[    {id: 1, nombre: "nombreProducto", precio: 5000, img:"img/ASPjbIMG.jpg", descripcion:"Descripcion de producto", categoria:"Quitamanchas"},
                    {id: 2, nombre: "nombreProducto", precio: 6000, img:"img/ASPjbIMG.jpg", descripcion:"Descripcion de producto", categoria:"Prelavado"},
                    {id: 3, nombre: "nombreProducto", precio: 4000, img:"img/ASPjbIMG.jpg", descripcion:"Descripcion de producto", categoria:"Quitamanchas"},
                    {id: 4, nombre: "nombreProducto", precio: 5000, img:"img/ASPjbIMG.jpg", descripcion:"Descripcion de producto", categoria:"Prelavado"},
                    {id: 5, nombre: "nombreProducto", precio: 8000, img:"img/ASPjbIMG.jpg", descripcion:"Descripcion de producto", categoria:"Quitamanchas"},
                    {id: 6, nombre: "nombreProducto", precio: 9000, img:"img/ASPjbIMG.jpg", descripcion:"Descripcion de producto", categoria:"Prelavado"},
                    {id: 7, nombre: "nombreProducto", precio: 500, img:"img/ASPjbIMG.jpg", descripcion:"Descripcion de producto", categoria:"Quitamanchas"},
                    {id: 8, nombre: "nombreProducto", precio: 4000, img:"img/ASPjbIMG.jpg", descripcion:"Descripcion de producto", categoria:"Prelavado"},
                    {id: 9, nombre: "nombreProducto", precio: 400, img:"img/ASPjbIMG.jpg", descripcion:"Descripcion de producto", categoria:"Quitamanchas"},
                    {id: 10, nombre: "nombreProducto", precio: 800, img:"img/ASPjbIMG.jpg", descripcion:"Descripcion de producto", categoria:"Prelavado"},
                    {id: 11, nombre: "nombreProducto", precio: 5000, img:"img/ASPjbIMG.jpg", descripcion:"Descripcion de producto", categoria:"Quitamanchas"},
                    {id: 12, nombre: "nombreProducto", precio: 9000, img:"img/ASPjbIMG.jpg", descripcion:"Descripcion de producto", categoria:"Prelavado"},
                    {id: 13, nombre: "nombreProducto", precio: 6000, img:"img/ASPjbIMG.jpg", descripcion:"Descripcion de producto", categoria:"Quitamanchas"},
                    {id: 14, nombre: "nombreProducto", precio: 100, img:"img/ASPjbIMG.jpg", descripcion:"Descripcion de producto", categoria:"Prelavado"},
                    {id: 15, nombre: "nombreProducto", precio: 1000, img:"img/ASPjbIMG.jpg", descripcion:"Descripcion de producto", categoria:"Quitamanchas"},
                    {id: 16, nombre: "nombreProducto", precio: 5000, img:"img/ASPjbIMG.jpg", descripcion:"Descripcion de producto", categoria:"Prelavado"},
                    {id: 17, nombre: "nombreProducto", precio: 5000, img:"img/ASPjbIMG.jpg", descripcion:"Descripcion de producto", categoria:"Potenciador De Aroma Para El Lavado"},
                    {id: 21, nombre: "nombreProducto", precio: 6000, img:"img/ASPjbIMG.jpg", descripcion:"Descripcion de producto", categoria:"Detergente Para Ropa"},
                    {id: 33, nombre: "nombreProducto", precio: 4000, img:"img/ASPjbIMG.jpg", descripcion:"Descripcion de producto", categoria:"Potenciador De Aroma Para El Lavado"},
                    {id: 44, nombre: "nombreProducto", precio: 5000, img:"img/ASPjbIMG.jpg", descripcion:"Descripcion de producto", categoria:"Detergente Para Ropa"},
                    {id: 55, nombre: "nombreProducto", precio: 8000, img:"img/ASPjbIMG.jpg", descripcion:"Descripcion de producto", categoria:"Potenciador De Aroma Para El Lavado"},
                    {id: 66, nombre: "nombreProducto", precio: 9000, img:"img/ASPjbIMG.jpg", descripcion:"Descripcion de producto", categoria:"Apresto"},
                    {id: 77, nombre: "nombreProducto", precio: 500, img:"img/ASPjbIMG.jpg", descripcion:"Descripcion de producto", categoria:"Potenciador De Aroma Para El Lavado"},
                    {id: 88, nombre: "nombreProducto", precio: 4000, img:"img/ASPjbIMG.jpg", descripcion:"Descripcion de producto", categoria:"Apresto"},
                    {id: 99, nombre: "nombreProducto", precio: 400, img:"img/ASPjbIMG.jpg", descripcion:"Descripcion de producto", categoria:"Jabón En Barra"},
                    {id: 100, nombre: "nombreProducto", precio: 800, img:"img/ASPjbIMG.jpg", descripcion:"Descripcion de producto", categoria:"Apresto"},
                    {id: 111, nombre: "nombreProducto", precio: 5000, img:"img/ASPjbIMG.jpg", descripcion:"Descripcion de producto", categoria:"Jabón En Barra"},
                    {id: 122, nombre: "nombreProducto", precio: 9000, img:"img/ASPjbIMG.jpg", descripcion:"Descripcion de producto", categoria:"Apresto"},
                    {id: 133, nombre: "nombreProducto", precio: 6000, img:"img/ASPjbIMG.jpg", descripcion:"Descripcion de producto", categoria:"Jabón En Barra"},
                    {id: 144, nombre: "nombreProducto", precio: 100, img:"img/ASPjbIMG.jpg", descripcion:"Descripcion de producto", categoria:"Apresto"},
                    {id: 155, nombre: "nombreProducto", precio: 1000, img:"img/ASPjbIMG.jpg", descripcion:"Descripcion de producto", categoria:"Jabón En Barra"},
                    {id: 166, nombre: "nombreProducto", precio: 5000, img:"img/ASPjbIMG.jpg", descripcion:"Descripcion de producto", categoria:"Apresto"},
                    {id: 167, nombre: "nombreProducto", precio: 5000, img:"img/ASPjbIMG.jpg", descripcion:"Descripcion de producto", categoria:"Jabón Liquido Y En Polvo"},
                    {id: 168, nombre: "nombreProducto", precio: 5000, img:"img/ASPjbIMG.jpg", descripcion:"Descripcion de producto", categoria:"Enjuagues Y Suavizantes"},
                    {id: 169, nombre: "nombreProducto", precio: 5000, img:"img/ASPjbIMG.jpg", descripcion:"Descripcion de producto", categoria:"Enjuagues Y Suavizantes"},
                    {id: 170, nombre: "nombreProducto", precio: 5000, img:"img/ASPjbIMG.jpg", descripcion:"Descripcion de producto", categoria:"Fragancias Para La Ropa"},
                ]


export let categorias =[    {id:1, nombre:"Jabón Liquido Y En Polvo", Categoria:"Limpieza"},
                            {id:2, nombre:"Enjuagues Y Suavizantes", Categoria:"Limpieza"},
                            {id:3, nombre:"Quitamanchas", Categoria:"Limpieza"},
                            {id:4, nombre:"Prelavado", Categoria:"Limpieza"},
                            {id:5, nombre:"Potenciador De Aroma Para El Lavado", Categoria:"Limpieza"},
                            {id:6, nombre:"Fragancias Para La Ropa", Categoria:"Limpieza"},
                            {id:7, nombre:"Apresto", Categoria:"Limpieza"},
                            {id:8, nombre:"Jabón En Barra", Categoria:"Limpieza"},
                            {id:9, nombre:"Detergente Para Ropa", Categoria:"Limpieza"},]


export let carrito = [];
